# Generated by Django 2.1.5 on 2019-02-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190220_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='                                                                                                                                                                     <django.db.models.fields.TextField>...', max_length=1000),
        ),
    ]
